Server api updates
Quicr/new-libquicr pull request #4
Opened 2023-01-20 10:33 UTC by suhasHere

2023-01-20 23:42 UTC, fluffy commented on include/quicr/quicr_server.h
> +                               bytes&& payload) = 0;
I don't like the name payload. I think it should name the token

2023-01-20 23:42 UTC, fluffy commented on include/quicr/quicr_server.h
> +  virtual void onPublishIntent(const QUICRContext& context_id,
I think we can get rid of context_id

2023-01-20 23:42 UTC, fluffy commented on include/quicr/quicr_server.h
> +                                 uint64_t best_before,
I think this need to be in milii seconds after the message was recieved so it can be perhasp uint16_t

2023-01-20 23:45 UTC, TimEvens requested changes
Initial changes... Discuss more next week.

2023-01-20 23:45 UTC, TimEvens commented on include/quicr/quicr_server.h
> +  virtual void onPublishIntent(const QUICRContext& context_id,
Remove ```context_id``` throughout.

2023-01-20 23:45 UTC, TimEvens commented on include/quicr/quicr_server.h
> +  QuicRServer(ITransport&, ServerDelegate& delegate) explicit;
missing ```ITransport``` name?

2023-01-22 14:55 UTC, suhasHere commented
Merging the changes since they were discussed in the meeting.

2023-01-22 14:55 UTC, merged

2023-01-22 14:56 UTC, suhasHere commented
Merged the changes as they very trivial and were discussed during the meeting